
// name: "Pizza Dip",
// description: "Cheese on cheese on cheese, on sauce on cheese. Also pepperoni.",
// user_name: "Edward",
// main_image_url: "http://i.imgur.com/HKZtBKi.webm",
// video_url: "https://www.youtube.com/watch?v=lrIRTs-K0Jg",
// ingredients: [
// 	{name: "Milk", quantity: "1/2 cup"},
// 	{name: "Cream Cheese", quantity: "6 oz"},
// 	{name: "Mozzarella", quantity: "1/2 cup, shredded"},
// 	{name: "Parmesan", quantity: "1/2 cup"},
// 	{name: "Mariana", quantity: "3/4 cup"},
// 	{name: "Pepperoni", quantity: "A lot"}
// ],
// prep_time: "10 min",
// cook_time: "10 min",
// serving_size: "4-5",
// steps: ["Preheat oven to 450 degrees F / 230 degrees C.",
// 		"On medium heat, combine the milk, cream cheese, mozzarella, and parmesan until it melts down. Stir until it reaches the consistency of a sauce.",
// 		"Pour cheese mixture into a serving dish and layer marinara, more shredded mozzarella cheese, and pepperonis on top.",
// 		"Stick this in the oven and let it bake until bubbly.", 
// 		"Dip bread into this cheesy goodness. Enjoy!"],
// tags: ["sidedish", "appetizer", "pizza", "dip", "superbowl", "potluck", "cheese"]


// name: "Bacon-Wrapped Pesto Chicken",
// description: "Can you watch this chicken recipe without salivating?",
// user_name: "Edward",
// main_image_url: "http://i.imgur.com/qG2D1yw.webm",
// video_url: "https://www.youtube.com/watch?v=OamKvzFLK7A",
// ingredients: [
// 	{name: "Bacon Strips", quantity: "5"},
// 	{name: "Chicken Breast", quantity: "1"},
// 	{name: "Pesto", quantity: "Your choice"},
// 	{name: "Shredded Cheese", quantity: "Your choice"}
// ],
// prep_time: "5 min",
// cook_time: "25 min",
// serving_size: "1-2",
// steps: ["Preheat oven to 400 degrees F / 204 degrees C.",
// 		"Lie out bacon strips horizontally next to each other and put chicken breast perpendicularly on top of the strips.",
// 		"Cut through the center of the chicken breast without cutting through the whole thing, enough to create a pocket. Pour pesto into said pocket.",
// 		"Sprinkle shredded cheese on top of pesto and wrap the whole chicken breast with the layers of bacon.", 
// 		"Place in the oven and bake for 25 minutes (for ½ lb. chicken).",
// 		"Remove from oven and serve on a plate. Enjoy!"],
// tags: ["entree", "bacon", "homemade", "pesto", "nom"]


// name: "Iced Coffee Popsicle",
// description: "For the perfect summer morning.",
// user_name: "Edward",
// main_image_url: "http://i.imgur.com/NAmUG6r.webm",
// video_url: "https://www.youtube.com/watch?v=MjVnug8OznA",
// ingredients: [
// 	{name: "Strong Coffee", quantity: "5"},
// 	{name: "Sweet Condensed Milk", quantity: "1"},
// 	{name: "Espresso Beans", quantity: "Your choice"}],
// prep_time: "3 min",
// cook_time: "120 min",
// serving_size: "1",
// steps: ["Brew some strong coffee beforehand and pour said coffee into a tall shot glass.",
// 		"Grab a popsicle stick and dip in the condensed milk. Stick that back into the shot glass and mix.",
// 		"Throw some espresso beans inside the mixture for some crunch.",
// 		"Poke a cupcake case on top of the shot glass through the popsicle stick.", 
// 		"Place in the freezer for around 2 hours.",
// 		"Run glass under lukewarm water until the popsicle mixture can budge out. Enjoy!"],
// tags: ["desserts", "summer", "frozentreats", "coffee", "milk"]


// name: "3-Ingredient Nutella Brownies",
// description: "You’ll  never want to make regular brownies ever again.",
// user_name: "Edward",
// main_image_url: "http://i.imgur.com/sqWKkXt.webm",
// video_url: "https://www.youtube.com/watch?v=sXWZSpr9XFo",
// ingredients: [
// 	{name: "Nutella", quantity: "1.5 cup"},
// 	{name: "Eggs", quantity: "2"},
// 	{name: "Flour", quantity: "0.5 cup"}],
// prep_time: "5 min",
// cook_time: "15 min",
// serving_size: "12-16 brownies",
// steps: ["Preheat the oven to 350 degrees F / 177 degrees C.",
// 		"Combine Nutella, eggs, and flour into a bowl. Mix thoroughly until the batter is smooth.",
// 		"Prep the baking pan with oil or melted butter.",
// 		"Pour mixture into the pan evenly.", 
// 		"Bake in the oven for 15 minutes.",
// 		"Slice brownies into squares and enjoy!"],
// tags: ["desserts", "chocolate", "brownies", "nutella", "yum", "3ingredients"]


// name: "Bacon-Wrapped Sriracha Onion Rings",
// description: "Sriracha, bacon, AND onion rings?! What’s not to love?",
// user_name: "Edward",
// main_image_url: "http://i.imgur.com/AcyuYbR.webm",
// video_url: "https://www.youtube.com/watch?v=DTaCqmWy-6s",
// ingredients: [
// 	{name: "White Onions", quantity: "4"},
// 	{name: "Sriracha", quantity: "1 bottle"},
// 	{name: "Bacon Strips", quantity: "1 bag"},
// 	{name: "Mayo", quantity: "2 tbsp"},
// 	{name: "Lime Juice", quantity: "2 tsp"}],
// prep_time: "10 min",
// cook_time: "40 min",
// serving_size: "3-4",
// steps: ["Preheat the oven to 400 degrees F / 204 degrees C.",
// 		"Slice onions in half carefully and peel apart circular layers.",
// 		"Brush Sriracha generously along the inside/outside of the rings.",
// 		"Use about 3-4 strips of bacon per ring and wrap around the circular edges.", 
// 		"Stick a skewer across the onion ring and place them on a baking pan, lined with aluminum foil.",
// 		"Bake for 40 minutes and then let cool.",
// 		"For a dipping sauce, mix mayo, Srirarcha (2 tbsp.), and lime juice together."],
// tags: ["sidedishes", "appetizers", "bacon", "sriracha", "onionrings"]


// name: "3-Ingredient Pancakes ",
// description: "This egg-cellent recipe is bananas.",
// user_name: "Edward",
// main_image_url: "http://i.imgur.com/7g4Gova.webm",
// video_url: "https://www.youtube.com/watch?v=UNDei0Lo2dg",
// ingredients: [
// 	{name: "Banana", quantity: "1"},
// 	{name: "Eggs", quantity: "2"},
// 	{name: "Ground Cinnamon", quantity: "1 tsp"},
// 	{name: "Butter", quantity: "Optional"},
// 	{name: "Syrup", quantity: "Optional"}],
// prep_time: "5 min",
// cook_time: "15 min",
// serving_size: "1-2",
// steps: ["Peel banana and mash into a bowl.",
// 		"Crack two eggs into the banana mash and sprinkle ground cinnamon. Mix thoroughly.",
// 		"Pour mixture onto a pan and flip when bubble appear on surface and begin to break.",
// 		"Serve on a plate with spread butter and drizzled syrup. Enjoy!"],
// tags: ["breakfast", "easy", "3ingredients", "homemade", "pancakes", "yum"]